// Generated by LiveScript 1.5.0
(function(){
  var loadProviders, loadCoins;
  loadProviders = require('./load-providers.ls');
  loadCoins = require('./load-coins.ls');
  module.exports = function(mode, cb){
    return loadCoins(mode, function(err, coins){
      if (err != null) {
        return cb(err);
      }
      return loadProviders(mode, function(err, providers){
        if (err != null) {
          return cb(err);
        }
        return buildApi(coins, providers, mode, function(err, api){
          if (err != null) {
            return cb(err);
          }
          return cb(null, api);
        });
      });
    });
  };
}).call(this);
