// Generated by LiveScript 1.6.0
(function(){
  var requireLs, loadProviders, loadCoins, buildApi;
  requireLs = require('require-ls');
  loadProviders = require('./load-providers.ls');
  loadCoins = require('./load-coins.ls');
  buildApi = require('./build-api.ls');
  module.exports = function(config, cb){
    return loadCoins(config, function(err, coins){
      if (err != null) {
        return cb(err);
      }
      return loadProviders(config, function(err, providers){
        if (err != null) {
          return cb(err);
        }
        return buildApi(coins, providers, config, function(err, api){
          if (err != null) {
            return cb(err);
          }
          return cb(null, api);
        });
      });
    });
  };
}).call(this);
