// Generated by LiveScript 1.6.0
(function(){
  var btc, dash, eth, etc, ltc, xrp, usdt, xlm, trx, xmr, ref$, objToPairs, pairsToObj, filter, onlyCoins, extendCoins, toString$ = {}.toString;
  btc = require('./plugins/btc-coin.ls');
  dash = require('./plugins/dash-coin.ls');
  eth = require('./plugins/eth-coin.ls');
  etc = require('./plugins/etc-coin.ls');
  ltc = require('./plugins/ltc-coin.ls');
  xrp = require('./plugins/xrp-coin.ls');
  usdt = require('./plugins/usdt-coin.ls');
  xlm = require('./plugins/xlm-coin.ls');
  trx = require('./plugins/trx-coin.ls');
  xmr = require('./plugins/xmr-coin.ls');
  ref$ = require('prelude-ls'), objToPairs = ref$.objToPairs, pairsToObj = ref$.pairsToObj, filter = ref$.filter;
  onlyCoins = function(plugins){
    return pairsToObj(
    filter(function(it){
      var ref$;
      return ((ref$ = it[1]) != null ? ref$.type : void 8) === 'coin';
    })(
    objToPairs(
    plugins)));
  };
  extendCoins = function(coins, config){
    if (toString$.call(config.plugins).slice(8, -1) !== 'Object') {
      return;
    }
    return importAll$(coins, onlyCoins(config.plugins));
  };
  module.exports = function(config, cb){
    var def;
    def = {
      btc: btc,
      dash: dash,
      eth: eth,
      ltc: ltc,
      usdt: usdt,
      xlm: xlm,
      trx: trx,
      xmr: xmr,
      etc: etc
    };
    extendCoins(def, config);
    return cb(null, def);
  };
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
