// Generated by LiveScript 1.6.0
(function(){
  var configParser;
  configParser = require('../config-parser.js');
  module.exports = function(cb){
    var config;
    config = configParser('testnet');
    if (config.getModeFor('eth') !== 'testnet') {
      return cb("Wrong network " + config.getModeFor('eth') + ", expected testnet");
    }
    config = configParser('testnet, ethnamed for eth');
    if (config.getModeFor('eth') !== 'ethnamed') {
      return cb("Wrong network " + config.getModeFor('eth') + ", expected ethnamed");
    }
    return cb(null);
  };
}).call(this);
