// Generated by LiveScript 1.6.0
(function(){
  var buildWeb3t, mnemonic;
  buildWeb3t = require('../index.js');
  mnemonic = require('./mnemonic.js');
  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0;
  buildWeb3t('mainnet', function(err, web3t){
    var ref$, createAccount, getBalance, calcFee;
    ref$ = web3t.eth, createAccount = ref$.createAccount, getBalance = ref$.getBalance, calcFee = ref$.calcFee;
    return createAccount({
      mnemonic: mnemonic,
      index: 0
    }, function(err, account){
      var to;
      to = '0x35b686646ffc646969953dbe12252d554fe6c5ce';
      return calcFee({
        account: account,
        to: to,
        data: '0x',
        feeType: 'auto',
        amount: "0"
      }, function(err, fee){
        return console.log(err, fee);
      });
    });
  });
}).call(this);
