// Generated by LiveScript 1.6.0
(function(){
  var buildWeb3t, checkFields, testCoins, checkConfig, main;
  buildWeb3t = require('../index.js');
  checkFields = require('./check-fields.js');
  testCoins = require('./test-coins.js');
  checkConfig = require('./check-config.js');
  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0;
  main = function(network, cb){
    return checkConfig(function(err){
      if (err != null) {
        return cb(err);
      }
      return buildWeb3t(network, function(err, web3t){
        if (err != null) {
          return cb(err);
        }
        return checkFields(web3t, function(err){
          if (err != null) {
            return cb(err);
          }
          return testCoins(web3t, function(err){
            if (err != null) {
              return cb(err);
            }
            return cb(null);
          });
        });
      });
    });
  };
  main('testnet, ethnamed for eth', function(err, result){
    if (err != null) {
      return console.error(err);
    }
    return console.log(result);
  });
}).call(this);
