// Generated by LiveScript 1.6.0
(function(){
  module.exports = "xmr bch btg ltc eth eos xem ada dash btc zec bcn";
  module.exports = "cat thumb picture vehicle olympic dawn air wealth crop whale glare sheriff note diagram fly";
}).call(this);
