// Generated by LiveScript 1.6.0
(function(){
  var gobyteCoin, ref$, readFileSync, writeFileSync, text;
  gobyteCoin = require('../plugins/gobyte-coin.js');
  ref$ = require('fs'), readFileSync = ref$.readFileSync, writeFileSync = ref$.writeFileSync;
  text = JSON.stringify(gobyteCoin, null, 4);
  writeFileSync('./gobyte-coin.json', text);
}).call(this);
