// Generated by LiveScript 1.6.0
(function(){
  var buildWeb3t, mnemonic;
  buildWeb3t = require('../index.ls');
  mnemonic = "step world panther frog tiny express ensure wear soldier album make kit";
  buildWeb3t("mainnet", function(err, web3t){
    return web3t.btc.createAccount({
      mnemonic: mnemonic,
      index: 1
    }, function(err, account){
      return console.log(err, account != null ? account.address : void 8);
    });
  });
}).call(this);
