// Generated by LiveScript 1.6.0
(function(){
  var pow, arrayToHex, verify;
  pow = require('proof-of-work');
  arrayToHex = function(arr){
    return arr.map(function(it){
      return +it.toString(16);
    }).join('');
  };
  verify = function(arg$, cb){
    var nonce, complexity, solution, size, n, prefix, validity, verifier, hex, result;
    nonce = arg$.nonce, complexity = arg$.complexity, solution = arg$.solution;
    size = 1024;
    n = 16;
    prefix = Buffer.from(nonce, 'hex');
    validity = 60000;
    verifier = new pow.Verifier({
      size: size,
      n: n,
      complexity: complexity,
      prefix: prefix,
      validity: validity
    });
    hex = (function(){
      switch (false) {
      case !(solution.indexOf(',') > -1):
        return solution.split(',');
      default:
        return solution;
      }
    }());
    result = verifier.check(Buffer.from(hex, "hex"));
    return cb(null, result);
  };
  module.exports = verify;
}).call(this);
