// Generated by LiveScript 1.6.0
(function(){
  var pow, solver, solve;
  pow = require('proof-of-work');
  solver = new pow.Solver();
  solve = function(arg$, cb){
    var nonce, complexity, prefix;
    nonce = arg$.nonce, complexity = arg$.complexity;
    prefix = Buffer.from(nonce, 'hex');
    nonce = solver.solve(complexity, prefix);
    return cb(null, nonce.toString('hex'));
  };
  module.exports = solve;
}).call(this);
