// Generated by LiveScript 1.6.0
(function(){
  var keythereum;
  keythereum = require('keythereum');
  module.exports = function(complexity){
    var dk, nonce;
    complexity == null && (complexity = 18);
    dk = keythereum.create();
    nonce = keythereum.privateKeyToAddress(dk.privateKey);
    return {
      complexity: complexity,
      nonce: nonce
    };
  };
}).call(this);
