// Generated by LiveScript 1.6.0
(function(){
  var powVerify, powSolve, powGen, task;
  powVerify = require('./pow-verify.js');
  powSolve = require('./pow-solve.js');
  powGen = require('./pow-gen.js');
  task = powGen(19);
  powSolve(task, function(err, solution){
    console.log(err, solution);
    return powVerify((import$({
      solution: solution
    }, task)), function(err, res){
      return console.log(err, res);
    });
  });
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
