// Generated by LiveScript 1.6.0
(function(){
  var stringify, ref$, filter, map, foldl, each, find, sum, values, plus, minus, times, div, get, post, jsonParse, deadline, BitcoinLib, bip39, getBitcoinFullpairByIndex, calcFee, getKeys, extendNum, extend, toHex, getApiUrl, addValue, getOutputs, createTransaction, transformTx, getTransactions, getDec, checkDecodedData, pushTx, checkTxStatus, str, getTotalReceived, getUnconfirmedBalance, getData, getBalance, out$ = typeof exports != 'undefined' && exports || this, toString$ = {}.toString;
  stringify = require('qs').stringify;
  ref$ = require('prelude-ls'), filter = ref$.filter, map = ref$.map, foldl = ref$.foldl, each = ref$.each, find = ref$.find, sum = ref$.sum, values = ref$.values;
  ref$ = require('../math.js'), plus = ref$.plus, minus = ref$.minus, times = ref$.times, div = ref$.div;
  ref$ = require('./superagent.js'), get = ref$.get, post = ref$.post;
  jsonParse = require('../json-parse.js');
  deadline = require('../deadline.js');
  ref$ = require('./deps.js'), BitcoinLib = ref$.BitcoinLib, bip39 = ref$.bip39;
  getBitcoinFullpairByIndex = function(mnemonic, index, network){
    var seed, hdnode, address, privateKey, publicKey;
    seed = bip39.mnemonicToSeedHex(mnemonic);
    hdnode = BitcoinLib.HDNode.fromSeedHex(seed, network).derive(index);
    address = hdnode.getAddress();
    privateKey = hdnode.keyPair.toWIF();
    publicKey = hdnode.getPublicKeyBuffer().toString('hex');
    return {
      address: address,
      privateKey: privateKey,
      publicKey: publicKey
    };
  };
  out$.calcFee = calcFee = function(arg$, cb){
    var network, tx, txType, account, feeType, o, txFee, ref$;
    network = arg$.network, tx = arg$.tx, txType = arg$.txType, account = arg$.account, feeType = arg$.feeType;
    o = network != null ? network.txFeeOptions : void 8;
    txFee = (ref$ = o != null ? o[feeType] : void 8) != null
      ? ref$
      : (ref$ = network.txFee) != null ? ref$ : 0;
    if (feeType !== 'auto') {
      return cb(null, txFee);
    }
    return get(getApiUrl(network) + "/utils/estimatefee?nbBlocks=6").timeout({
      deadline: deadline
    }).end(function(err, data){
      var vals, exists, ref$, calcedFee;
      if (err != null) {
        return cb(err);
      }
      vals = values(data.body);
      exists = (ref$ = vals[0]) != null
        ? ref$
        : -1;
      calcedFee = (function(){
        switch (false) {
        case vals[0] !== -1:
          return network.txFee;
        default:
          return vals[0];
        }
      }());
      return cb(null, calcedFee);
    });
  };
  out$.getKeys = getKeys = function(arg$, cb){
    var network, mnemonic, index, result;
    network = arg$.network, mnemonic = arg$.mnemonic, index = arg$.index;
    result = getBitcoinFullpairByIndex(mnemonic, index, network);
    return cb(null, result);
  };
  extendNum = function(str, fixed){
    if (str.length >= fixed) {
      return str;
    }
    return extendNum("0" + str, fixed);
  };
  extend = curry$(function(add, json){
    return import$(json, add);
  });
  toHex = function(num, fixed){
    var n;
    n = (+num).toString(16);
    return extendNum(n, fixed);
  };
  getApiUrl = function(network){
    var apiName, ref$;
    apiName = (ref$ = network.api.apiName) != null ? ref$ : 'api';
    return network.api.apiUrlBtc + "/" + apiName;
  };
  addValue = curry$(function(network, it){
    var dec;
    dec = getDec(network);
    return it.value = (function(){
      switch (false) {
      case it.satoshis == null:
        return it.satoshis;
      case it.amount == null:
        return times(it.amount, dec);
      default:
        return 0;
      }
    }());
  });
  getOutputs = curry$(function(arg$, cb){
    var network, address, url;
    network = arg$.network, address = arg$.address;
    url = network.api.url;
    return get(getApiUrl(network) + "/addr/" + address + "/utxo").timeout({
      deadline: deadline
    }).end(function(err, data){
      if (err != null) {
        return cb(err);
      }
      if (toString$.call(data.body).slice(8, -1) !== 'Array') {
        return cb("Result is not an array");
      }
      return function(it){
        return cb(null, it);
      }(
      map(extend({
        network: network,
        address: address
      }))(
      each(addValue(network))(
      data.body)));
    });
  });
  out$.createTransaction = createTransaction = function(arg$, cb){
    var network, account, recipient, amount, amountFee, feeType, txType, spender;
    network = arg$.network, account = arg$.account, recipient = arg$.recipient, amount = arg$.amount, amountFee = arg$.amountFee, feeType = arg$.feeType, txType = arg$.txType, spender = arg$.spender;
    return getOutputs({
      network: network,
      address: account.address
    }, function(err, outputs){
      var isNoValue, dec, value, fee, dust, total;
      if (err != null) {
        return cb(err);
      }
      if (outputs.length === 0) {
        return cb('Not Enough Funds (Unspent Outputs)');
      }
      isNoValue = find(function(it){
        return it.value == null;
      })(
      outputs);
      if (isNoValue) {
        return cb('Each output should have a value');
      }
      dec = getDec(network);
      value = times(amount, dec);
      fee = times(amountFee, dec);
      dust = 546;
      total = sum(
      map(function(it){
        return it.value;
      })(
      outputs));
      if (isNaN(total)) {
        return cb('Total is NaN');
      }
      if (+minus(total, fee) <= 0) {
        return cb("Balance is not enough to send tx");
      }
      return getBalance({
        network: network,
        address: account.address
      }, function(err, omniBalance){
        var tx, simple_send, data, omniOutput, rest, apply, sign, rawtx;
        if (err != null) {
          return cb(err);
        }
        if (+omniBalance < +amount) {
          return cb("Balance is not enough to send this amount");
        }
        tx = new BitcoinLib.TransactionBuilder(network);
        simple_send = ["6f6d6e69", toHex(0, 4), toHex(network.propertyid, 12), toHex(value, 16)];
        data = Buffer.from(simple_send.join(''), 'hex');
        omniOutput = BitcoinLib.script.compile([BitcoinLib.opcodes.OP_RETURN, data]);
        rest = plus(minus(total, fee), dust);
        tx.addOutput(recipient, dust);
        tx.addOutput(omniOutput, 0);
        if (+rest !== 0) {
          tx.addOutput(account.address, +rest);
        }
        apply = function(output, i){
          return tx.addInput(output.txid, output.vout, 0xfffffffe);
        };
        sign = function(output, i){
          var key;
          key = BitcoinLib.ECPair.fromWIF(account.privateKey, network);
          return tx.sign(i, key);
        };
        outputs.forEach(apply);
        outputs.forEach(sign);
        rawtx = tx.build().toHex();
        return cb(null, {
          rawtx: rawtx
        });
      });
    });
  };
  transformTx = curry$(function(arg$, t){
    var network, address, url, dec, tx, amount, time, fee, from, to;
    network = arg$.network, address = arg$.address;
    url = network.api.url;
    network = 'usdt';
    dec = getDec(network);
    tx = t.txid;
    amount = t.amount;
    time = t.blocktime;
    url = url + "/tx/" + tx;
    fee = t.fee;
    from = t.sendingaddress;
    to = t.referenceaddress;
    return {
      network: network,
      tx: tx,
      amount: amount,
      fee: fee,
      time: time,
      url: url,
      from: from,
      to: to
    };
  });
  out$.getTransactions = getTransactions = function(arg$, cb){
    var network, address, apiUrl, req;
    network = arg$.network, address = arg$.address;
    apiUrl = network.api.apiUrl;
    req = {
      addr: address
    };
    return post(apiUrl + "/v1/address/addr/details/", req).type('form').end(function(err, data){
      var ref$, txs;
      if (err != null) {
        return cb(err);
      }
      if (toString$.call(data).slice(8, -1) !== 'Object') {
        return cb("expected object");
      }
      if (toString$.call((ref$ = data.body) != null ? ref$.transactions : void 8).slice(8, -1) !== 'Array') {
        return cb("expected array");
      }
      txs = map(transformTx({
        network: network,
        address: address
      }))(
      filter(function(it){
        return +it.propertyid === +network.propertyid;
      })(
      data.body.transactions));
      return cb(null, txs);
    });
  };
  getDec = function(network){
    var decimals;
    decimals = network.decimals;
    return Math.pow(10, decimals);
  };
  out$.checkDecodedData = checkDecodedData = function(decodedData, data){
    return cb(null, '');
  };
  out$.pushTx = pushTx = curry$(function(arg$, cb){
    var network, rawtx;
    network = arg$.network, rawtx = arg$.rawtx;
    return post(getApiUrl(network) + "/tx/send", {
      rawtx: rawtx
    }).end(function(err, res){
      var ref$;
      if (err != null) {
        return cb(err);
      }
      return cb(null, (ref$ = res.body) != null ? ref$.txid : void 8);
    });
  });
  out$.checkTxStatus = checkTxStatus = function(arg$, cb){
    var network, tx;
    network = arg$.network, tx = arg$.tx;
    return cb("Not Implemented");
  };
  str = function(it){
    return (it != null ? it : "").toString();
  };
  out$.getTotalReceived = getTotalReceived = function(arg$, cb){
    var address, network;
    address = arg$.address, network = arg$.network;
    return getTransactions({
      address: address,
      network: network
    }, function(err, txs){
      var total;
      total = foldl(plus, 0)(
      map(function(it){
        return it.amount;
      })(
      filter(function(it){
        return it.to === address;
      })(
      txs)));
      return cb(null, total);
    });
  };
  out$.getUnconfirmedBalance = getUnconfirmedBalance = function(arg$, cb){
    var network, address;
    network = arg$.network, address = arg$.address;
    return cb("Not Implemented");
  };
  getData = function(data, cb){
    var res, err;
    try {
      res = JSON.parse(data.text);
      return cb(null, res);
    } catch (e$) {
      err = e$;
      return cb(err);
    }
  };
  out$.getBalance = getBalance = function(arg$, cb){
    var network, address, apiUrl, req;
    network = arg$.network, address = arg$.address;
    apiUrl = network.api.apiUrl;
    req = {
      addr: address
    };
    return post(apiUrl + "/v1/address/addr/", req).type('form').end(function(err, data){
      if (err != null) {
        return cb(err);
      }
      return getData(data, function(err, body){
        var balance, dec, value;
        if (err != null) {
          return cb(err);
        }
        if (toString$.call(body != null ? body.balance : void 8).slice(8, -1) !== 'Array') {
          return cb("expected balance array. got " + data.text);
        }
        balance = find(function(it){
          return str(it.id) === str(network.propertyid);
        })(
        data.body.balance);
        if (balance == null) {
          return cb(null, 0);
        }
        dec = getDec(network);
        value = div(balance.value, dec);
        return cb(null, value);
      });
    });
  };
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
