// Generated by LiveScript 1.6.0
(function(){
  var Wallet, VelasCrypto, ref$, map, foldl, filter, get, post, plus, minus, times, div, fromHex, bip39, bignumber, toCallback, calcFee, getKeys, transformTx, getTransactions, bigInt, getUnspents, createTransaction, pushTx, checkTxStatus, getTotalReceived, getUnconfirmedBalance, getBalance, out$ = typeof exports != 'undefined' && exports || this, toString$ = {}.toString;
  Wallet = require('../node_modules_embed/vlx-wallet/Crypto/Wallet.js')['default'];
  VelasCrypto = require('../node_modules_embed/vlx-wallet/Crypto/index.js')['default'];
  ref$ = require('prelude-ls'), map = ref$.map, foldl = ref$.foldl, filter = ref$.filter;
  ref$ = require('./superagent.js'), get = ref$.get, post = ref$.post;
  ref$ = require('../math.js'), plus = ref$.plus, minus = ref$.minus, times = ref$.times, div = ref$.div, fromHex = ref$.fromHex;
  bip39 = require('bip39');
  bignumber = require('bignumber.js');
  toCallback = function(p, cb){
    p.then(function(res){
      return cb(null, res);
    });
    return p['catch'](function(res){
      return cb(res);
    });
  };
  out$.calcFee = calcFee = function(arg$, cb){
    var network, feeType, account, amount, to, data;
    network = arg$.network, feeType = arg$.feeType, account = arg$.account, amount = arg$.amount, to = arg$.to, data = arg$.data;
    return cb(null, network.txFee);
  };
  out$.getKeys = getKeys = function(arg$, cb){
    var network, mnemonic, index;
    network = arg$.network, mnemonic = arg$.mnemonic, index = arg$.index;
    return toCallback(VelasCrypto.init(), function(err, vc){
      var seedBuffer, seed, res, address, privateKey;
      seedBuffer = bip39.mnemonicToSeed(mnemonic);
      seed = seedBuffer.toString('hex');
      res = vc.keysGen.fromSeed(seed, 'm/' + index + '\'');
      address = res.toWallet().Base58Address;
      privateKey = res.privateKey;
      return cb(null, {
        address: address,
        privateKey: privateKey
      });
    });
  };
  transformTx = function(tx){
    return tx;
  };
  out$.getTransactions = getTransactions = function(arg$, cb){
    var network, address;
    network = arg$.network, address = arg$.address;
    return get(network.api.historyUrl.replace(':address', address)).end(function(err, data){
      if (err != null) {
        return cb(err);
      }
      return cb(null, data.body);
    });
  };
  bigInt = function(it){
    return new bignumber(it);
  };
  getUnspents = function(arg$, cb){
    var network, address, baseUrl;
    network = arg$.network, address = arg$.address;
    baseUrl = network.api.apiUrl;
    return get(baseUrl + "/unspent/" + address).end(function(err, res){
      var unspentsNative;
      unspentsNative = res.body;
      if (toString$.call(unspentsNative).slice(8, -1) !== 'Array') {
        return cb("expected array");
      }
      if (err != null) {
        return cb(err);
      }
      return cb(null, res.body);
    });
  };
  out$.createTransaction = createTransaction = curry$(function(arg$, cb){
    var network, account, recipient, amount, amountFee, data, feeType, txType;
    network = arg$.network, account = arg$.account, recipient = arg$.recipient, amount = arg$.amount, amountFee = arg$.amountFee, data = arg$.data, feeType = arg$.feeType, txType = arg$.txType;
    if (!Wallet.IsValidAddress(account.address)) {
      return cb("Given address is not valid Velas address");
    }
    if (!Wallet.IsValidAddress(recipient)) {
      return cb("Recipient address is not valid Velas address");
    }
    return getUnspents({
      network: network,
      address: account.address
    }, function(err, unspentsNative){
      var unspents;
      if (err != null) {
        return cb(err);
      }
      if (unspents.length === 0) {
        return cb("there is not any unspents");
      }
      unspents = map(function(it){
        return {
          hash: it.hash,
          index: it.index,
          value: bigInt(it.value)
        };
      })(
      unspentsNative);
      return calcFee({
        network: network,
        feeType: feeType,
        account: account,
        amount: amount,
        to: recipient,
        data: data
      }, function(err, fee){
        if (err != null) {
          return cb(err);
        }
        return toCallback(VelasCrypto.init(), function(err, vc){
          var hdKeys, wallet, amountSatoshi, amountSatoshiBigInt, feeBigInt, txUnsigned, tx, rawtx;
          if (err != null) {
            return cb(err);
          }
          hdKeys = vc.keysGen.fromPrivateKey(account.privateKey);
          wallet = hdKeys.toWallet();
          amountSatoshi = times(amount, Math.pow(10, network.decimals));
          amountSatoshiBigInt = bigInt(amountSatoshi);
          feeBigInt = bigInt(fee);
          txUnsigned = vc.tx.generate(unspents, amountSatoshiBigInt, hdKeys, account.address, recipient, feeBigInt);
          tx = txUnsigned.sign();
          rawtx = tx.toJSON();
          return cb(null, {
            rawtx: rawtx
          });
        });
      });
    });
  });
  out$.pushTx = pushTx = curry$(function(arg$, cb){
    var network, rawtx, baseUrl;
    network = arg$.network, rawtx = arg$.rawtx;
    baseUrl = network.api.apiUrl;
    return post(baseUrl + "/send", rawtx).end(function(err, tx){
      if (err != null) {
        return cb(err);
      }
      return cb(null, tx);
    });
  });
  out$.checkTxStatus = checkTxStatus = function(arg$, cb){
    var network, tx;
    network = arg$.network, tx = arg$.tx;
    return cb("Not Implemented");
  };
  out$.getTotalReceived = getTotalReceived = function(arg$, cb){
    var address, network;
    address = arg$.address, network = arg$.network;
    if (!Wallet.IsValidAddress(address)) {
      return cb("Given address is not valid Velas address");
    }
    return cb(null, 0);
  };
  out$.getUnconfirmedBalance = getUnconfirmedBalance = function(arg$, cb){
    var network, address;
    network = arg$.network, address = arg$.address;
    if (!Wallet.IsValidAddress(address)) {
      return cb("Given address is not valid Velas address");
    }
    return cb(null, 0);
  };
  out$.getBalance = getBalance = function(arg$, cb){
    var network, address;
    network = arg$.network, address = arg$.address;
    if (!Wallet.IsValidAddress(address)) {
      return cb("Given address is not valid Velas address");
    }
    return getUnspents({
      network: network,
      address: address
    }, function(err, unspentsNative){
      var balance;
      if (err != null) {
        return cb(err);
      }
      if (unspentsNative.length === 0) {
        return cb(null, 0);
      }
      balance = foldl(plus, 0)(
      map(function(it){
        return it.value;
      })(
      unspentsNative));
      return cb(null, balance);
    });
  };
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
