// Generated by LiveScript 1.6.0
(function(){
  var topupCoinsByMask, networks, type, enabled, token, image, address, out$ = typeof exports != 'undefined' && exports || this;
  out$.topupCoinsByMask = topupCoinsByMask = "*";
  out$.networks = networks = "mainnet";
  out$.type = type = 'topup';
  out$.enabled = enabled = true;
  out$.token = token = 'trycrypto';
  out$.image = image = 'https://res.cloudinary.com/nixar-work/image/upload/v1547940596/logo3-bl.png';
  out$.address = address = "https://trycrypto.net/?from=EUR&to={token}&address={address}";
}).call(this);
