// Generated by LiveScript 1.6.0
(function(){
  var url, mainnet, testnet, color, type, enabled, token, image, usdInfo, out$ = typeof exports != 'undefined' && exports || this;
  url = 'https://royalswap.com';
  out$.mainnet = mainnet = {
    decimals: 2,
    txFee: 0,
    txFeeOptions: {
      withdraw: 0
    },
    messagePrefix: 'Ethereum',
    mask: '0x0000000000000000000000000000000000000000',
    api: {
      provider: 'rst',
      url: url + "/fiat/explorer",
      apiUrl: url + "/fiat-token/usd_ac_rs",
      web3Provider: url + "/fiat-token/usd_ac_rs"
    }
  };
  out$.testnet = testnet = {
    disabled: true
  };
  out$.color = color = "#62C272";
  out$.type = type = 'coin';
  out$.enabled = enabled = true;
  out$.token = token = 'usd_ac_rs';
  out$.image = image = "https://bitcoin-debit-cards.com/wp-content/uploads/2017/12/advcash-app.png";
  out$.usdInfo = usdInfo = 1;
}).call(this);
