// Generated by LiveScript 1.6.0
(function(){
  var mainnet, testnet, type, enabled, token, image, usdInfo, out$ = typeof exports != 'undefined' && exports || this;
  out$.mainnet = mainnet = {
    decimals: 8,
    txFee: '0.001',
    mask: '3P000000000000000000000000000000000',
    messagePrefix: 'Waves',
    api: {
      provider: 'waves',
      url: 'https://wavesexplorer.com'
    }
  };
  out$.testnet = testnet = {
    decimals: 8,
    txFee: '0.001',
    mask: '3P000000000000000000000000000000000',
    messagePrefix: 'Waves',
    api: {
      provider: 'waves',
      url: 'https://wavesexplorer.com'
    }
  };
  out$.type = type = 'coin';
  out$.enabled = enabled = false;
  out$.token = token = 'waves';
  out$.image = image = '//res.cloudinary.com/nixar-work/image/upload/v1525380100/waves-icon.png';
  out$.usdInfo = usdInfo = "url(https://min-api.cryptocompare.com/data/pricemulti?fsyms=WAVES&tsyms=USD).WAVES.USD";
}).call(this);
