// Generated by LiveScript 1.6.0
(function(){
  var nem, proxy, mainnet, testnet, type, enabled, token, image, usdInfo, out$ = typeof exports != 'undefined' && exports || this;
  nem = require('nem-sdk')['default'];
  proxy = 'https://cors-anywhere.herokuapp.com/';
  proxy = '';
  out$.mainnet = mainnet = {
    decimals: 6,
    txFee: '0.05',
    id: 104,
    prefix: "68",
    char: "N",
    api: {
      provider: 'xem',
      nodeAddress: nem.model.nodes.defaultMainnet,
      nodePort: nem.model.nodes.defaultPort,
      url: nem.model.nodes.mainnetExplorer.replace('/transfer/', ''),
      apiUrl: proxy + "http://chain.nem.ninja/api3"
    }
  };
  out$.testnet = testnet = {
    decimals: 6,
    txFee: '0.05',
    id: -104,
    prefix: "98",
    char: "T",
    api: {
      provider: 'xem',
      nodeAddress: nem.model.nodes.defaultTestnet,
      nodePort: nem.model.nodes.defaultPort,
      url: nem.model.nodes.testnetExplorer.replace('/transfer/', ''),
      apiUrl: proxy + "http://bob.nem.ninja:8765/api3"
    }
  };
  out$.type = type = 'coin';
  out$.enabled = enabled = true;
  out$.token = token = 'xem';
  out$.image = image = './res/nem-ethnamed.png';
  out$.usdInfo = usdInfo = "url(https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH,LTC,DASH,XEM,USDT,ETC&tsyms=USD).XEM.USD";
}).call(this);
