// Generated by LiveScript 1.6.0
(function(){
  var mainnet, testnet, type, color, enabled, token, image, usdInfo, out$ = typeof exports != 'undefined' && exports || this;
  out$.mainnet = mainnet = {
    messagePrefix: 'Monero',
    api: {
      provider: 'cryptonote',
      url: 'https://xmrchain.com',
      apiUrl: 'https://xmrchain.com/api',
      nodeUrl: 'http://node.moneroworld.com:18089/json_rpc'
    }
  };
  out$.testnet = testnet = {
    messagePrefix: 'Monero',
    api: {
      provider: 'cryptonote',
      url: 'https://testnet.xmrchain.com',
      apiUrl: 'https://testnet.xmrchain.com/api',
      nodeUrl: 'testnet.xmrchain.net:28081/json_rpc'
    }
  };
  out$.type = type = 'coin';
  out$.color = color = '#FF6601';
  out$.enabled = enabled = false;
  out$.token = token = 'xmr';
  out$.image = image = './res/xml-ethnamed.png';
  out$.usdInfo = usdInfo = "url(https://min-api.cryptocompare.com/data/pricemulti?fsyms=XMR&tsyms=USD).XMR.USD";
}).call(this);
