// Generated by LiveScript 1.6.0
(function(){
  var mainnet, testnet, type, enabled, token, image, usdInfo, out$ = typeof exports != 'undefined' && exports || this;
  out$.mainnet = mainnet = {
    decimals: 8,
    txFee: '0.0001',
    mask: 't000000000000000000000000000000000',
    api: {
      provider: 'insightzec',
      url: 'https://zcashnetwork.info',
      decimal: 8
    },
    messagePrefix: '\x18Zcash Signed Message:\n',
    bip32: {
      'public': 0x0488b21e,
      'private': 0x05358394
    },
    pubKeyHash: 0x1CB8,
    scriptHash: 0x1CBD,
    wif: 0x80
  };
  out$.testnet = testnet = {
    decimals: 8,
    txFee: '0.0001',
    mask: 'tm00000000000000000000000000000000',
    api: {
      provider: 'insightzec',
      url: 'https://explorer.testnet.z.cash',
      decimal: 8
    },
    topup: 'https://faucet.testnet.z.cash/',
    messagePrefix: '\x18Zcash Signed Message:\n',
    bip32: {
      'public': 0x043587cf,
      'private': 0x04358394
    },
    pubKeyHash: 0x1d25,
    scriptHash: 0x1cba,
    wif: 0xef
  };
  out$.type = type = 'coin';
  out$.enabled = enabled = false;
  out$.token = token = 'zec';
  out$.image = image = './res/zcash_icon.png';
  out$.usdInfo = usdInfo = "url(https://min-api.cryptocompare.com/data/pricemulti?fsyms=ZEC&tsyms=USD).ZEC.USD";
}).call(this);
